---

# This is an example of configuration to train DA3C Continuous with gym's BipedalWalker-v2.
#
# To run this training navigate to empty directory next to relaax repo,
# open three terminals there and run:
# relaax-parameter-server --config ../relaax/config/da3cc_gym_walker.yaml
# relaax-rlx-server --config ../relaax/config/da3cc_gym_walker.yaml
# ../relaax/environments/OpenAI_Gym/main --rlx-server localhost:7001 --env BipedalWalker-v2

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: checkpoints/a3c_gym_walker
  --log-level: WARNING
  --metrics-dir: metrics_gym_walker

relaax-rlx-server:
  --bind: localhost:7001
  --parameter-server: localhost:7000
  --log-level: WARNING

algorithm:
  path: ../relaax/algorithms/da3c_cont

  action_size: 4                  # action size for the given environment
  state_size: [24]                # array of dimensions for the input observation
  history_len: 1                  # number of observations to stack in state
  episode_len: 5                  # local loop size for one episode
  gpu: false                      # to use GPU, set to the True
  lstm: false                     # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  initial_learning_rate: 5e-5
  entropy_beta: 1e-3              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  RMSProp:
    decay: 0.99
    epsilon: 0.1
    gradient_norm_clipping: 40
